### ISSUE TITLE
Bug: test-data in autogluon/AutoGluon-Text-Classification.ipynb

### ISSUE THREAD

**Issue by sugspi** [aws-samples/amazon-sagemaker-examples-jp#46]
I found a bug to create test.csv file.

Please change "train_index" to "test_index" in the code,
like below:

[before]
np.savetxt('test.csv',labeled_df.iloc[train_index].values, fmt="%s,%i") 
[after]
np.savetxt('test.csv',labeled_df.iloc[test_index].values, fmt="%s,%i")

**Comment by harusametime** [comment]
Commit https://github.com/aws-samples/amazon-sagemaker-examples-jp/commit/2b1de5a84ee38586e4051f65e43990663133c86f fixed this issue. Thanks!
